language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GCOV=gcov-7"

    - os: osx
      osx_image: xcode10.2
      env:
        - MATRIX_EVAL="GCOV=gcov"


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 -DVERILOGAST_BUILD_TESTS=ON ..
  - cmake --build .
  - ctest
  # Check that installation works
  - sudo make install
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      test -f /usr/local/lib/libverilogAST.dylib 
    else 
      test -f /usr/local/lib/libverilogAST.so 
    fi
  - test -f /usr/local/include/verilogAST.hpp

after_success:
  - bash <(curl -s https://codecov.io/bash)
