language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10.2


before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
      chmod +x miniconda.sh
      ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
      export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
      hash -r
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda create -q -n test-env python=3.7
      source activate test-env
      conda install pip
    fi
  - pip install --user cpp-coveralls


script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 -DVERILOGAST_BUILD_TESTS=ON ..
  - cmake --build .
  - ctest
  # Check that installation works
  - sudo make install
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      test -f /usr/local/lib/libverilogAST.dylib 
    else 
      test -f /usr/local/lib/libverilogAST.so 
    fi
  - test -f /usr/local/include/verilogAST.hpp

after_success:
  - coveralls --gcov gcov-7 --root .. -E ".*CMakeFiles.*" -E ".*googletest-src.*" -E ".*tests/.*.cpp.*" -e miniconda
